// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeptunBackend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeptunBackend.Migrations
{
    [DbContext(typeof(NeptunDbContext))]
    [Migration("20250510071742_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeptunBackend.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentNeptunCode")
                        .HasColumnType("character varying(5)");

                    b.Property<string>("TeacherNeptunCode")
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNeptunCode");

                    b.HasIndex("TeacherNeptunCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("NeptunBackend.Models.Person", b =>
                {
                    b.Property<string>("NeptunCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NeptunCode");

                    b.ToTable((string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NeptunBackend.Models.Student", b =>
                {
                    b.HasBaseType("NeptunBackend.Models.Person");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NeptunBackend.Models.Teacher", b =>
                {
                    b.HasBaseType("NeptunBackend.Models.Person");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("NeptunBackend.Models.Course", b =>
                {
                    b.HasOne("NeptunBackend.Models.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentNeptunCode");

                    b.HasOne("NeptunBackend.Models.Teacher", null)
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherNeptunCode");
                });

            modelBuilder.Entity("NeptunBackend.Models.Student", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("NeptunBackend.Models.Teacher", b =>
                {
                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
